spring.application.name=VehicleTelemetry
# ==============================================================
# CONFIGURACIÓN DE KAFKA
# ==============================================================
spring.kafka.bootstrap-servers=localhost:9092

# Consumidor
spring.kafka.consumer.group-id=telemetry-processor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Productor
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ==============================================================
# CONFIGURACIÓN DE BASE DE DATOS H2 (EN MEMORIA)
# ==============================================================
spring.datasource.url=${DATASOURCE}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==============================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==============================================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update